server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: customer

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: ton
    password: 123456

  security:
    user:
      name: ton
      password: password
      role: ADMIN
